version: '3.8'

services:
  tasks-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: tasks-service:latest
    ports:
      - "3308:3308"
    environment:
      - ENV=production
    depends_on:
      - db
    volumes:
      - .:/app
    command: fastapi dev app/main.py --host 0.0.0.0 --port 3308

  db:
    image: mysql:8.0
    container_name: taskchat_db
    restart: always
    environment:
      
      MYSQL_DATABASE: parentapp
      MYSQL_USER: avnadmin
      
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:


